In [2]:
import numpy as np

In [32]:
npt = 100

joint_init = np.array([-2.68, 90])
joint_final = np.array([-0.875, 135])

traj_jnt_shoulder_1 = np.linspace(joint_init[0], joint_final[0], npt, endpoint=True) #npt is no of points ex:100
traj_jnt_shoulder_2 = np.linspace(joint_init[1], joint_final[1], npt, endpoint=True) #npt is no of points ex:100

In [33]:
joint_init*180/np.pi

array([-153.5526891 , 5156.62015618])

In [34]:
joint_final*180/np.pi

array([ -50.13380707, 7734.93023427])

In [35]:
traj_jnt_shoulder_1

array([-2.68      , -2.66176768, -2.64353535, -2.62530303, -2.60707071,
       -2.58883838, -2.57060606, -2.55237374, -2.53414141, -2.51590909,
       -2.49767677, -2.47944444, -2.46121212, -2.4429798 , -2.42474747,
       -2.40651515, -2.38828283, -2.37005051, -2.35181818, -2.33358586,
       -2.31535354, -2.29712121, -2.27888889, -2.26065657, -2.24242424,
       -2.22419192, -2.2059596 , -2.18772727, -2.16949495, -2.15126263,
       -2.1330303 , -2.11479798, -2.09656566, -2.07833333, -2.06010101,
       -2.04186869, -2.02363636, -2.00540404, -1.98717172, -1.96893939,
       -1.95070707, -1.93247475, -1.91424242, -1.8960101 , -1.87777778,
       -1.85954545, -1.84131313, -1.82308081, -1.80484848, -1.78661616,
       -1.76838384, -1.75015152, -1.73191919, -1.71368687, -1.69545455,
       -1.67722222, -1.6589899 , -1.64075758, -1.62252525, -1.60429293,
       -1.58606061, -1.56782828, -1.54959596, -1.53136364, -1.51313131,
       -1.49489899, -1.47666667, -1.45843434, -1.44020202, -1.42

In [16]:
traj_jnt_shoulder_2

array([ 90.        ,  90.45454545,  90.90909091,  91.36363636,
        91.81818182,  92.27272727,  92.72727273,  93.18181818,
        93.63636364,  94.09090909,  94.54545455,  95.        ,
        95.45454545,  95.90909091,  96.36363636,  96.81818182,
        97.27272727,  97.72727273,  98.18181818,  98.63636364,
        99.09090909,  99.54545455, 100.        , 100.45454545,
       100.90909091, 101.36363636, 101.81818182, 102.27272727,
       102.72727273, 103.18181818, 103.63636364, 104.09090909,
       104.54545455, 105.        , 105.45454545, 105.90909091,
       106.36363636, 106.81818182, 107.27272727, 107.72727273,
       108.18181818, 108.63636364, 109.09090909, 109.54545455,
       110.        , 110.45454545, 110.90909091, 111.36363636,
       111.81818182, 112.27272727, 112.72727273, 113.18181818,
       113.63636364, 114.09090909, 114.54545455, 115.        ,
       115.45454545, 115.90909091, 116.36363636, 116.81818182,
       117.27272727, 117.72727273, 118.18181818, 118.63

In [36]:
 # move to default pos
num_step = 100
joint_traj = []
init_dof_pos = [-0.857, 0.105]
target_pos = -1.8

for i in range(num_step):
    alpha = i / num_step
    #for j in range(dof_size): #comment to only move calf_FL
    j = 0
    joint_traj.append(init_dof_pos[j] * (1 - alpha) + target_pos * alpha)

In [37]:
joint_traj

[-0.857,
 -0.86643,
 -0.87586,
 -0.88529,
 -0.89472,
 -0.9041499999999999,
 -0.91358,
 -0.9230099999999999,
 -0.93244,
 -0.9418700000000001,
 -0.9513,
 -0.9607300000000001,
 -0.9701599999999999,
 -0.97959,
 -0.98902,
 -0.99845,
 -1.00788,
 -1.0173100000000002,
 -1.02674,
 -1.03617,
 -1.0456,
 -1.05503,
 -1.06446,
 -1.07389,
 -1.08332,
 -1.0927499999999999,
 -1.10218,
 -1.11161,
 -1.12104,
 -1.1304699999999999,
 -1.1399,
 -1.14933,
 -1.15876,
 -1.16819,
 -1.1776200000000001,
 -1.1870500000000002,
 -1.19648,
 -1.20591,
 -1.21534,
 -1.22477,
 -1.2342,
 -1.24363,
 -1.25306,
 -1.2624900000000001,
 -1.2719200000000002,
 -1.2813500000000002,
 -1.29078,
 -1.3002099999999999,
 -1.30964,
 -1.31907,
 -1.3285,
 -1.33793,
 -1.3473600000000001,
 -1.3567900000000002,
 -1.36622,
 -1.37565,
 -1.3850800000000003,
 -1.3945100000000001,
 -1.40394,
 -1.41337,
 -1.4228,
 -1.4322300000000001,
 -1.4416600000000002,
 -1.4510900000000002,
 -1.46052,
 -1.46995,
 -1.4793800000000001,
 -1.4888100000000002,
 -1.498

In [39]:
import numpy as np

info = {"qpos_error_history": np.ones(3*12)}


In [59]:
pos_error = np.ones(12)*3


qpos_error_history = np.roll(info["qpos_error_history"], 12)  # Shift elements forward by 12


In [60]:
qpos_error_history

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4.])

In [58]:
qpos_error_history[:12] = pos_error  # Overwrite first 12 elements

info["qpos_error_history"] = qpos_error_history

In [20]:
qpos_error_history

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2.])

In [1]:
import onnx

In [9]:
model = onnx.load("/home/rajath/Documents/Go2_mjx/utils/outputs/go2_policy-5.onnx")
print(onnx.helper.printable_graph(model.graph))

graph main_graph (
  %state[FLOAT, 1x48]
) initializers (
  %mean[FLOAT, 48]
  %std[FLOAT, 48]
  %mlp_block.hidden_0.weight[FLOAT, 256x48]
  %mlp_block.hidden_0.bias[FLOAT, 256]
  %mlp_block.hidden_1.weight[FLOAT, 256x256]
  %mlp_block.hidden_1.bias[FLOAT, 256]
  %mlp_block.hidden_2.weight[FLOAT, 256x256]
  %mlp_block.hidden_2.bias[FLOAT, 256]
  %mlp_block.hidden_3.weight[FLOAT, 256x256]
  %mlp_block.hidden_3.bias[FLOAT, 256]
  %mlp_block.hidden_4.weight[FLOAT, 256x256]
  %mlp_block.hidden_4.bias[FLOAT, 256]
  %mlp_block.hidden_5.weight[FLOAT, 24x256]
  %mlp_block.hidden_5.bias[FLOAT, 24]
) {
  %/Sub_output_0 = Sub(%state, %mean)
  %/Div_output_0 = Div(%/Sub_output_0, %std)
  %/mlp_block/hidden_0/Gemm_output_0 = Gemm[alpha = 1, beta = 1, transB = 1](%/Div_output_0, %mlp_block.hidden_0.weight, %mlp_block.hidden_0.bias)
  %/mlp_block/activation/Sigmoid_output_0 = Sigmoid(%/mlp_block/hidden_0/Gemm_output_0)
  %/mlp_block/activation/Mul_output_0 = Mul(%/mlp_block/hidden_0/Gemm_output_0, %/

In [10]:
path = "utils/weights/go2_params-5.pkl"