In [2]:
import numpy as np

In [32]:
npt = 100

joint_init = np.array([-2.68, 90])
joint_final = np.array([-0.875, 135])

traj_jnt_shoulder_1 = np.linspace(joint_init[0], joint_final[0], npt, endpoint=True) #npt is no of points ex:100
traj_jnt_shoulder_2 = np.linspace(joint_init[1], joint_final[1], npt, endpoint=True) #npt is no of points ex:100

In [33]:
joint_init*180/np.pi

array([-153.5526891 , 5156.62015618])

In [34]:
joint_final*180/np.pi

array([ -50.13380707, 7734.93023427])

In [35]:
traj_jnt_shoulder_1

array([-2.68      , -2.66176768, -2.64353535, -2.62530303, -2.60707071,
       -2.58883838, -2.57060606, -2.55237374, -2.53414141, -2.51590909,
       -2.49767677, -2.47944444, -2.46121212, -2.4429798 , -2.42474747,
       -2.40651515, -2.38828283, -2.37005051, -2.35181818, -2.33358586,
       -2.31535354, -2.29712121, -2.27888889, -2.26065657, -2.24242424,
       -2.22419192, -2.2059596 , -2.18772727, -2.16949495, -2.15126263,
       -2.1330303 , -2.11479798, -2.09656566, -2.07833333, -2.06010101,
       -2.04186869, -2.02363636, -2.00540404, -1.98717172, -1.96893939,
       -1.95070707, -1.93247475, -1.91424242, -1.8960101 , -1.87777778,
       -1.85954545, -1.84131313, -1.82308081, -1.80484848, -1.78661616,
       -1.76838384, -1.75015152, -1.73191919, -1.71368687, -1.69545455,
       -1.67722222, -1.6589899 , -1.64075758, -1.62252525, -1.60429293,
       -1.58606061, -1.56782828, -1.54959596, -1.53136364, -1.51313131,
       -1.49489899, -1.47666667, -1.45843434, -1.44020202, -1.42

In [16]:
traj_jnt_shoulder_2

array([ 90.        ,  90.45454545,  90.90909091,  91.36363636,
        91.81818182,  92.27272727,  92.72727273,  93.18181818,
        93.63636364,  94.09090909,  94.54545455,  95.        ,
        95.45454545,  95.90909091,  96.36363636,  96.81818182,
        97.27272727,  97.72727273,  98.18181818,  98.63636364,
        99.09090909,  99.54545455, 100.        , 100.45454545,
       100.90909091, 101.36363636, 101.81818182, 102.27272727,
       102.72727273, 103.18181818, 103.63636364, 104.09090909,
       104.54545455, 105.        , 105.45454545, 105.90909091,
       106.36363636, 106.81818182, 107.27272727, 107.72727273,
       108.18181818, 108.63636364, 109.09090909, 109.54545455,
       110.        , 110.45454545, 110.90909091, 111.36363636,
       111.81818182, 112.27272727, 112.72727273, 113.18181818,
       113.63636364, 114.09090909, 114.54545455, 115.        ,
       115.45454545, 115.90909091, 116.36363636, 116.81818182,
       117.27272727, 117.72727273, 118.18181818, 118.63

In [ ]:
 # move to default pos
num_step = 100
joint_traj = []
init_dof_pos = [-0.857, 0.105]
target_pos = -1.8

for i in range(num_step):
    alpha = i / num_step
    #for j in range(dof_size): #comment to only move calf_FL
    j = 0
    joint_traj.append(init_dof_pos[j] * (1 - alpha) + target_pos * alpha)